In [97]:
import nltk
import string
import re
import pandas as pd
import contractions
import unicodedata
from autocorrect import Speller
import inflect
import emoji
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

In [55]:
df = pd.read_csv(r'C:\\Users\\july.rabot\\Documents\\Mes_Projets\\Ning\\SMS_test.csv', encoding='latin-1')

In [56]:
df.head()

   S. No.                                       Message_body Label
0       1  UpgrdCentre Orange customer, you may now claim...  Spam
1       2  Loan for any purpose £500 - £75,000. Homeowner...  Spam
2       3  Congrats! Nokia 3650 video camera phone is you...  Spam
3       4  URGENT! Your Mobile number has been awarded wi...  Spam
4       5  Someone has contacted our dating service and e...  Spam

In [57]:
# lowercasing
def text_lowercase(texte):
    return texte.lower()

df['Message_body'] = df['Message_body'].apply(text_lowercase)

In [58]:
df.head()

   S. No.                                       Message_body Label
0       1  upgrdcentre orange customer, you may now claim...  Spam
1       2  loan for any purpose £500 - £75,000. homeowner...  Spam
2       3  congrats! nokia 3650 video camera phone is you...  Spam
3       4  urgent! your mobile number has been awarded wi...  Spam
4       5  someone has contacted our dating service and e...  Spam

In [59]:
def fix_contractions(texte):
    return contractions.fix(str(texte))


df['Message_body'] = df['Message_body'].apply(fix_contractions)

In [60]:
df.head()

   S. No.                                       Message_body Label
0       1  upgrdcentre orange customer, you may now claim...  Spam
1       2  loan for any purpose £500 - £75,000. homeowner...  Spam
2       3  congrats! nokia 3650 video camera phone is you...  Spam
3       4  urgent! your mobile number has been awarded wi...  Spam
4       5  someone has contacted our dating service and e...  Spam

In [61]:
def correct_with_autocorrect(text, lang='en'):
    """Correct spelling using autocorrect library for English."""
    spell = Speller(lang=lang)
    return spell(text)

df['Message_body'] = df['Message_body'].apply(correct_with_autocorrect)

In [62]:
df.head()

   S. No.                                       Message_body Label
0       1  upgrdcentre orange customer, you may now claim...  Spam
1       2  loan for any purpose £500 - £75,000. homeowner...  Spam
2       3  contrast! nokia 3650 video camera phone is you...  Spam
3       4  urgent! your mobile number has been awarded wi...  Spam
4       5  someone has contacted our dating service and e...  Spam

In [63]:
def standardize_accented_chars(text):
    return unicodedata.normalize('NFKD', text).encode('ascii', 'ignore').decode('utf-8', 'ignore')

df['Message_body'] = df['Message_body'].apply(standardize_accented_chars)

In [64]:
df.head()

   S. No.                                       Message_body Label
0       1  upgrdcentre orange customer, you may now claim...  Spam
1       2  loan for any purpose 500 - 75,000. homeowners ...  Spam
2       3  contrast! nokia 3650 video camera phone is you...  Spam
3       4  urgent! your mobile number has been awarded wi...  Spam
4       5  someone has contacted our dating service and e...  Spam

In [65]:
def remove_html_tagst_regex(text):
    """Remove HTML tags using regular expression"""
    clean = re.compile('<.*?>')
    return re.sub(clean, '', text)


df['Message_body'] = df['Message_body'].apply(remove_html_tagst_regex)

In [66]:
df.head()

   S. No.                                       Message_body Label
0       1  upgrdcentre orange customer, you may now claim...  Spam
1       2  loan for any purpose 500 - 75,000. homeowners ...  Spam
2       3  contrast! nokia 3650 video camera phone is you...  Spam
3       4  urgent! your mobile number has been awarded wi...  Spam
4       5  someone has contacted our dating service and e...  Spam

In [67]:
def remove_numbers(text):
    result = re.sub(r'\d+', '<number>', text)
    return result

df['Message_body'] = df['Message_body'].apply(remove_numbers)

In [68]:
def remove_numbers(text):
    result = re.sub(r'\d{7,}', '<number>', text)
    return result

df['Message_body'] = df['Message_body'].apply(remove_numbers)

In [69]:
p = inflect.engine()

#convert numbers into words
def convert_number(text):
    #split string into list of words
    temp_str = text.split()
    #initialise empty list
    new_string = []

    for word in temp_str:
        # if word is a digit, convert the digit
        # to numbers and append into the new_string list
        if word.isdigit():
            temp=p.number_to_words(word)
            new_string.append(temp)
        # append the word as it is
        else:
            new_string.append(word)

    # join the words of the new_string to form a string
    temp_str = ' '.join(new_string)
    return temp_str

df['Message_body'] = df['Message_body'].apply(convert_number)

In [70]:
df.head()

   S. No.                                       Message_body Label
0       1  upgrdcentre orange customer, you may now claim...  Spam
1       2  loan for any purpose <number> - <number>,<numb...  Spam
2       3  contrast! nokia <number> video camera phone is...  Spam
3       4  urgent! your mobile number has been awarded wi...  Spam
4       5  someone has contacted our dating service and e...  Spam

In [71]:
regular_punct = list(string.punctuation)
print(regular_punct)

['!', '"', '#', '$', '%', '&', "'", '(', ')', '*', '+', ',', '-', '.', '/', ':', ';', '<', '=', '>', '?', '@', '[', '\\', ']', '^', '_', '`', '{', '|', '}', '~']

In [74]:
def remove_punctuation(text, punct_list):
    text = str(text)
    for punc in punct_list:
        if punc in text:
            text = text.replace(punc, '')
    return text.strip()


df['Message_body'] = df['Message_body'].apply(remove_punctuation, args=(regular_punct,))

In [75]:
df.head()

   S. No.                                       Message_body Label
0       1  upgrdcentre orange customer you may now claim ...  Spam
1       2  loan for any purpose number  numbernumber home...  Spam
2       3  contrast nokia number video camera phone is yo...  Spam
3       4  urgent your mobile number has been awarded wit...  Spam
4       5  someone has contacted our dating service and e...  Spam

In [76]:
def remove_whitespace(text):
        return " ".join(text.split())

df['Message_body'] = df['Message_body'].apply(remove_whitespace)

In [78]:
def remove_emojis_emoji_library(text):
    """Remove emojis using the emoji library."""
    return emoji.replace_emoji(text, replace = '')

df['Message_body'] = df['Message_body'].apply(remove_emojis_emoji_library)

In [79]:
url_pattern = []
url_pattern.append(re.compile(r'https:?//\S+'))
url_pattern.append(re.compile(r'http:?//\S+'))
url_pattern.append(re.compile(r'www.\S+'))

def remove_urls2(text):
    for pattern in url_pattern:
        text=pattern.sub('<this link>', text)
    return text

df['Message_body'] = df['Message_body'].apply(remove_urls2)

In [ ]:

nltk.download('punkt') 
nltk.download('punkt_tab')


df['Message_body'] = df['Message_body'].apply(nltk.word_tokenize)

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\july.rabot\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\july.rabot\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

In [ ]:
stop_words = set(stopwords.words("english"))


def remove_stopwords(text):
    if type(text) == list:
        filtered_text = [word for word in text if word.lower() not in stop_words]
        return filtered_text
    
    return text


df['Message_body'] = df['Message_body'].apply(remove_stopwords)

   S. No.                                       Message_body Label
0       1  [upgrdcentre, orange, customer, may, claim, fr...  Spam
1       2  [loan, purpose, number, numbernumber, homeowne...  Spam
2       3  [contrast, nokia, number, video, camera, phone...  Spam
3       4  [urgent, mobile, number, awarded, number, priz...  Spam
4       5  [someone, contacted, dating, service, entered,...  Spam

In [ ]:
stemmer = PorterStemmer()

def stem_words(text):
    if type(text) == list:
        stems = [stemmer.stem(word) for word in text]
        return stems

    return text

df['Message_body'] = df['Message_body'].apply(stem_words)

df.head()

   S. No.                                       Message_body Label
0       1  [upgrdcentr, orang, custom, may, claim, free, ...  Spam
1       2  [loan, purpos, number, numbernumb, homeown, te...  Spam
2       3  [contrast, nokia, number, video, camera, phone...  Spam
3       4  [urgent, mobil, number, award, number, prize, ...  Spam
4       5  [someon, contact, date, servic, enter, phone, ...  Spam

In [101]:
nltk.download('wordnet')

lemmatizer = WordNetLemmatizer()

def lemma_words(liste_de_mots):
    if type(liste_de_mots) == list:
        lemmas = [lemmatizer.lemmatize(word) for word in liste_de_mots]
        return lemmas
    
    return liste_de_mots

df['Message_body'] = df['Message_body'].apply(lemma_words)

df.head()

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\july.rabot\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

   S. No.                                       Message_body Label
0       1  [upgrdcentr, orang, custom, may, claim, free, ...  Spam
1       2  [loan, purpos, number, numbernumb, homeown, te...  Spam
2       3  [contrast, nokia, number, video, camera, phone...  Spam
3       4  [urgent, mobil, number, award, number, prize, ...  Spam
4       5  [someon, contact, date, servic, enter, phone, ...  Spam